<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Abstractions" Version="22.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameKeeper.Core\GameKeeper.Core.csproj" />
  </ItemGroup>

</Project>
